[package]
name = "executor"
version = "0.1.0"
edition = "2021"
authors = ["Keijack Wu"]
description = "A threadpool executor. "
readme = "README.md"
homepage = "https://github.com/keijack/rust-executor"
repository = "https://github.com/keijack/rust-executor"
license-file = "LICENSE"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
simple_logger = "^4"
